#!/usr/bin/env node
/**
 * generate-icon.js
 *
 * Generates all required app icons from assets/dingo-mascot.png (source).
 *
 * Requirements (install once on macOS):
 *   npm install -g sharp-cli          # PNG resizing
 *   # iconutil and sips ship with Xcode Command Line Tools
 *
 * Usage:
 *   node scripts/generate-icon.js
 *
 * Output:
 *   assets/icon.png       – 1024×1024 master PNG (used by electron-builder)
 *   assets/icon.icns      – macOS ICNS  (auto-generated by electron-builder
 *                           if icon.png ≥ 512 px, but also built here)
 *   assets/icon.ico       – Windows ICO (electron-builder handles this)
 *   assets/dmg-background.png – 540×380 DMG window background
 */

'use strict';

const { execSync, spawnSync } = require('child_process');
const fs   = require('fs');
const path = require('path');

const ROOT   = path.resolve(__dirname, '..');
const ASSETS = path.join(ROOT, 'assets');

// ── Helpers ──────────────────────────────────────────────────────────────────
function run(cmd, opts = {}) {
  console.log(`  $ ${cmd}`);
  const result = spawnSync(cmd, { shell: true, stdio: 'inherit', cwd: ROOT, ...opts });
  if (result.status !== 0) {
    console.error(`Command failed: ${cmd}`);
    process.exit(1);
  }
}

function requireTool(name, installHint) {
  const result = spawnSync(`which ${name}`, { shell: true });
  if (result.status !== 0) {
    console.error(`\nMissing tool: ${name}\n  ${installHint}\n`);
    process.exit(1);
  }
}

function checkSourceImage() {
  // Prefer a real PNG mascot; fall back to converting the SVG via sips.
  const png  = path.join(ASSETS, 'dingo-mascot.png');
  const svg  = path.join(ASSETS, 'dingo-mascot.svg');

  if (fs.existsSync(png)) {
    console.log('✓ Found dingo-mascot.png');
    return png;
  }

  if (fs.existsSync(svg)) {
    console.log('⚙  Converting dingo-mascot.svg → dingo-mascot.png via sips…');
    requireTool('sips', 'sips ships with macOS — no install needed');
    run(`sips -s format png "${svg}" --out "${png}" --resampleHeightWidth 1024 1024`);
    return png;
  }

  console.error('\nERROR: No source image found.\n' +
    'Place a high-resolution PNG (≥ 1024×1024) at assets/dingo-mascot.png\n' +
    'or keep assets/dingo-mascot.svg and this script will auto-convert it.\n');
  process.exit(1);
}

// ── Main ─────────────────────────────────────────────────────────────────────
console.log('\n🐕  Dingo Browser — Icon Generator\n');

if (process.platform !== 'darwin') {
  console.error('This script must be run on macOS (requires sips + iconutil).');
  console.log('\nOn other platforms, electron-builder will auto-generate icons');
  console.log('from assets/icon.png at build time — just supply a 1024×1024 PNG.\n');
  process.exit(0);
}

requireTool('sips',     'sips ships with macOS');
requireTool('iconutil', 'iconutil ships with Xcode Command Line Tools: xcode-select --install');

const sourcePng = checkSourceImage();

// 1. Master 1024×1024 icon.png
const masterPng = path.join(ASSETS, 'icon.png');
console.log('\n[1/3] Generating icon.png (1024×1024)…');
run(`sips -s format png "${sourcePng}" --out "${masterPng}" --resampleHeightWidth 1024 1024`);

// 2. ICNS via iconutil
console.log('\n[2/3] Generating icon.icns…');
const iconsetDir = path.join(ASSETS, 'icon.iconset');
fs.mkdirSync(iconsetDir, { recursive: true });

const sizes = [16, 32, 64, 128, 256, 512, 1024];
for (const sz of sizes) {
  const suffix = sz === 1024 ? '512@2x' : sz <= 512 ? `${sz}` : `${sz / 2}@2x`;
  run(`sips -s format png "${masterPng}" --out "${iconsetDir}/icon_${suffix}.png" --resampleHeightWidth ${sz} ${sz}`);
  if (sz <= 512) {
    // Also produce the @2x variant for HiDPI
    const sz2x = sz * 2;
    run(`sips -s format png "${masterPng}" --out "${iconsetDir}/icon_${sz}@2x.png" --resampleHeightWidth ${sz2x} ${sz2x}`);
  }
}

const icnsOut = path.join(ASSETS, 'icon.icns');
run(`iconutil -c icns "${iconsetDir}" -o "${icnsOut}"`);
fs.rmSync(iconsetDir, { recursive: true, force: true });
console.log(`  ✓ ${icnsOut}`);

// 3. DMG background (540×380, dark gradient)
console.log('\n[3/3] Generating dmg-background.png…');
const bgSvg = `<svg xmlns="http://www.w3.org/2000/svg" width="540" height="380">
  <defs>
    <linearGradient id="bg" x1="0" y1="0" x2="1" y2="1">
      <stop offset="0%"   stop-color="#0f0f1a"/>
      <stop offset="100%" stop-color="#1a0a06"/>
    </linearGradient>
  </defs>
  <rect width="540" height="380" fill="url(#bg)"/>
  <text x="270" y="340" text-anchor="middle" font-family="Helvetica Neue,sans-serif"
        font-size="13" font-weight="600" fill="rgba(255,255,255,0.25)"
        letter-spacing="2">DRAG TO INSTALL</text>
</svg>`;
const bgSvgPath = path.join(ASSETS, '_dmg-bg.svg');
fs.writeFileSync(bgSvgPath, bgSvg);
const bgPngPath = path.join(ASSETS, 'dmg-background.png');
run(`sips -s format png "${bgSvgPath}" --out "${bgPngPath}" --resampleHeightWidth 380 540`);
fs.unlinkSync(bgSvgPath);
console.log(`  ✓ ${bgPngPath}`);

console.log('\n✅  All icons generated.\n');
console.log('Next steps:');
console.log('  npm run build:mac          # arm64 DMG');
console.log('  npm run build:mac-universal # fat binary (arm64 + x64)\n');
